on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: actions/dependacombiner@v1
        with:
          name: 'Dylan'